general:
  name: 'new run'
  output_dir: './output'

data:
  image_height: 419
  image_width: 419
  train_data_dir: '../data/train/CytoPack'
  train_mask_dir: '/home/sidorov/Projects/QANetV2/data/generated/masks'
  train_temp_data_file: '../data/train/temp/CytoPack/clean_data.pkl'
  test_data_dir: '../data/test/Fluo-N2DH-GOWT1-ST'
  test_mask_dir: '../data/test/Fluo-N2DH-GOWT1-ST'
  inference_data_dir: '..data/inference/UNSW-AU-Fluo-N2DH-GOWT1'

augmentations:
  crop_height: 419
  crop_width: 419

model:
  in_channels: 1
  out_channels: 1

  architecture:
    conv2d_blocks:
      out_channels: [64, 128, 256, 256]
      kernel_sizes: [3, 3, 3, 3]

    fc_blocks:
      out_features: [128, 128]
      drop_rate: 0.4

  activation: 'swish'
  activation_relu_max_value: None
  activation_relu_negative_slope: 0.0
  activation_relu_threshold: 0.0
  activation_leaky_relu_alpha: 0.1

  drop_block: False
  drop_block_keep_prob: 0.1
  drop_block_block_size: 10

  kernel_regularizer_type: 'l2'
  kernel_regularizer_l1: 0.01
  kernel_regularizer_l2: 0.1
  kernel_regularizer_factor: 0.01
  kernel_regularizer_mode: 'rows'

training:
  load_checkpoint: False
  in_train_augmentation: False

  tr_checkpoint_file: '/home/sidorov/Projects/QANetV2/qanet/output/train/pytorch_2022-08-08_17-28-30/checkpoints/best_val_loss_chkpt.pth.tar'
  tf_checkpoint_dir: '/home/sidorov/Projects/QANetV2/qanet/output/train/tensor_flow_2022-11-24_13-15-16/checkpoints'
  tf_checkpoint_file: 'checkpoints/best_model.ckpt'

  epochs: 300
  batch_size: 16
  val_prop: 0.2
  num_train_workers: 4
  num_val_workers: 4
  pin_memory: True
  weighted_loss: False

  optimizer_maximize: False
  optimizer_foreach: None
  optimizer: 'adam'
  optimizer_lr: 0.0001
  optimizer_lr_decay: 0.001
  optimizer_beta_1: 0.9
  optimizer_beta_2: 0.999
  optimizer_rho: 0.9
  optimizer_amsgrad: False
  optimizer_weight_decay: 0.01
  optimizer_momentum: 0.1
  optimizer_dampening: 0.01
  optimizer_momentum_decay: 0.01
  optimizer_nesterov: False
  optimizer_centered: False

  # CALLBACKS
  min_improvement_delta: 0.00001

  # - Early Stopping
  early_stopping: True
  early_stopping_patience: 30
  early_stopping_monitor: 'val_loss'
  early_stopping_min_delta: 0.0001
  early_stopping_mode: 'auto'
  early_stopping_restore_best_weights: True
  early_stopping_verbose: 1

  # - LR Reduction Scheduler
  lr_reduction_scheduler: False
  lr_reduction_scheduler_patience: [150, 300]
  lr_reduction_scheduler_factor: 0.5
  lr_reduction_scheduler_min: 1e-9

  # - Terminate the training if the output is None
  terminate_on_nan: True

  # - LR Reduce on Plateau
  reduce_lr_on_plateau: True
  reduce_lr_on_plateau_patience: 10
  reduce_lr_on_plateau_factor: 0.9
  reduce_lr_on_plateau_monitor: 'val_loss'
  reduce_lr_on_plateau_min_delta: 0.0001
  reduce_lr_on_plateau_cooldown: 0
  reduce_lr_on_plateau_mode: 'auto'
  reduce_lr_on_plateau_verbose: 1
