general:
  project_name: 'QANetV2'
  experiment_name: 'new run'
  debug: False
  configs_dir: './global_configs'
  output_dir: './output'

data:
  reload_data: False
  image_height: 419
  image_width: 419

augmentations:
  crop_height: 256
  crop_width: 256
#  crop_height: 128
#  crop_width: 128

model:
  in_channels: 1
  out_channels: 1

  architecture:
    conv2d_blocks:
      out_channels: [64, 128, 256, 256]
      kernel_sizes: [3, 3, 3, 3]
    fc_blocks:
      out_features: [128, 128, 1]
      drop_rate: 0.2
#    conv2d_blocks:
#      out_channels: [32, 64, 128, 256]
#      kernel_sizes: [5, 5, 5, 5]
#
#    fc_blocks:
#      out_features: [512, 1024, 1]
#      drop_rate: 0.2

  architecture2:
    conv2d_blocks:
      out_channels: [64, 128, 256, 256]
      kernel_sizes: [3, 3, 3, 3]
    fc_blocks:
      out_features: [128, 128, 1]
      drop_rate: 0.2

  architecture3:
    conv2d_blocks:
      out_channels: [32, 64, 128, 256]
      kernel_sizes: [5, 5, 5, 5]

    fc_blocks:
      out_features: [512, 1024, 1]
      drop_rate: 0.2

#  activation: 'leaky_relu'
#  activation: 'relu'
  activation: 'swish'
  activation_relu_max_value: None
  activation_relu_negative_slope: 0.0
  activation_relu_threshold: 0.0
  activation_leaky_relu_alpha: 0.3

regularization:
  drop_block: False
  drop_block_keep_prob: 0.1
  drop_block_block_size: 10

  kernel_regularizer_type: None
#  kernel_regularizer_type: 'l2'
  kernel_regularizer_l1: 0.01
  kernel_regularizer_l2: 1.1
  kernel_regularizer_factor: 0.01
  kernel_regularizer_mode: 'rows'

callbacks:
  wandb_project_name: 'QANet_V2'
  wandb: True

  # - Tensor Board
  tensorboard: True
  tensorboard_launch: False
  tensorboard_write_images: True
  tensorboard_write_steps_per_second: True
  tensorboard_update_freq: 'epoch'
  tensorboard_scalars_log_interval: 1
  tensorboard_images_log_interval: 1

#  progress_log: False
  progress_log: True
  progress_log_interval: 1
  scatter_plot_figsize: (25, 15)
  scatter_plot_fontsize: 40

  # - Terminate on NaN
  terminate_on_nan: True

  # - Checkpoint
  checkpoint: True
  checkpoint_file_template: 'checkpoints/cp-{epoch:04d}.ckpt'  # <- may be used in case we want to save all teh check points, and not only the best
  checkpoint_file_best_model_file_name: 'best_model.ckpt'  # <- overwrites the second-best model weights in case MODEL_CHECKPOINT_SAVE_BEST_ONLY = True
  checkpoint_file_best_model: 'checkpoints/best_model.ckpt'  # <- overwrites the second-best model weights in case MODEL_CHECKPOINT_SAVE_BEST_ONLY = True
  checkpoint_monitor: 'val_loss'
  checkpoint_verbose: 1
  checkpoint_save_best_only: True
  checkpoint_mode: 'auto'
  checkpoint_save_weights_only: True
  checkpoint_save_freq: 'epoch'
  min_improvement_delta: 0.00001

  # - Early Stopping
  early_stopping: False
  early_stopping_patience: 30
  early_stopping_monitor: 'val_loss'
  early_stopping_min_delta: 0.00001
  early_stopping_mode: 'auto'
  early_stopping_restore_best_weights: True
  early_stopping_verbose: 1

  # - LR Reduction Scheduler
  lr_reduction_scheduler: 'None'
#  lr_reduction_scheduler: 'cosine'
  lr_reduction_scheduler_decay_steps: 30
  lr_reduction_scheduler_patience: [150, 300]
  lr_reduction_scheduler_factor: 0.3
  lr_reduction_scheduler_min: 1e-9

  # - Cyclical LR
  cyclical_lr: False
  cyclical_lr_init_lr: 0.0001
  cyclical_lr_max_lr: 0.0005
  cyclical_lr_step_size: 2 * 10  # 2 * IMAGES / BATCH_SIZE

  # - LR Reduce on Plateau
  reduce_lr_on_plateau: True
  reduce_lr_on_plateau_patience: 50
  reduce_lr_on_plateau_factor: 0.3
  reduce_lr_on_plateau_monitor: 'val_loss'
  reduce_lr_on_plateau_min_delta: 0.00001
  reduce_lr_on_plateau_cooldown: 0
  reduce_lr_on_plateau_mode: 'auto'
  reduce_lr_on_plateau_verbose: 1
  reduce_lr_on_plateau_min_lr: 0.00001

training:
  load_checkpoint: False
  in_train_augmentation: False

  seg_dir_postfix: 'GT'
  image_prefix: 't'
  seg_prefix: 'man_seg'
  seg_sub_dir: 'SEG'

  data_dir: '../data/train/CytoPack'
  mask_dir: '/home/sidorov/Projects/QANetV2/data/generated/masks'
  temp_data_file: '../data/train/temp/CytoPack/clean_data.pkl'

  tr_checkpoint_file: '/home/sidorov/Projects/QANetV2/qanet/output/train/pytorch_2022-08-08_17-28-30/checkpoints/best_val_loss_chkpt.pth.tar'
  checkpoint_dir: '/home/sidorov/Projects/QANetV2/qanet/output/train/tensor_flow_2022-11-24_13-15-16/checkpoints'
  tf_checkpoint_file: 'checkpoints/best_model.ckpt'

  loss: 'mse'
  metrics: []
  epochs: 300
  batch_size: 16
  val_batch_size: 16
  num_train_workers: 8
  val_prop: 0.05
  num_val_workers: 4
  pin_memory: True
  weighted_loss: False

  optimizer_maximize: False
  optimizer_foreach: None
#  optimizer: 'sgd'
  optimizer: 'adam'
  optimizer_lr: 0.001
  optimizer_lr_scheduler_reduction_points: [50, 100, 150, 250]
  optimizer_lr_scheduler_reduction_factor: 0.3
  optimizer_lr_decay: 0.001
  optimizer_beta_1: 0.9
  optimizer_beta_2: 0.999
  optimizer_rho: 0.9
  optimizer_amsgrad: False
  optimizer_weight_decay: 0.01
  optimizer_momentum: 0.1
  optimizer_dampening: 0.01
  optimizer_momentum_decay: 0.01
  optimizer_nesterov: True
  optimizer_centered: False

test:
  test_data: 'sim+'

  # - SIM+
  dataframe_file_sim+: '/home/sidorov/Projects/QANetV2/RefModels/Results/Fluo-N2DH-SIM+/seg_scores.csv'
  checkpoint_dir_sim+: '/home/sidorov/Projects/QANetV2/qanet/output/train/tensor_flow_dropblock_arch_2_256x256_2023-02-18_19-13-16/checkpoints'
#  checkpoint_dir_sim+: '/home/sidorov/Projects/QANetV2/qanet/output/train/tensor_flow_drop_block_last_cyclical_256x256_arch_2_2023-02-18_01-35-12/checkpoints'

  # - GOWT1
  dataframe_file_gowt1:  '/home/sidorov/Projects/QANetV2/RefModels/Results/Fluo-N2DH-GOWT1/seg_scores.csv'
  checkpoint_dir_gowt1: '/home/sidorov/Projects/QANetV2/qanet/output/train/tensor_flow_drop_block_last_cyclical_256x256_arch_2_2023-02-18_01-35-12/checkpoints'

  # - HeLa
  dataframe_file_hela: '/home/sidorov/Projects/QANetV2/RefModels/Results/Fluo-N2DL-HeLa/seg_scores.csv'
  checkpoint_dir_hela: '/home/sidorov/Projects/QANetV2/qanet/output/train/tensor_flow_drop_block_last_cyclical_256x256_arch_2_2023-02-18_01-35-12/checkpoints'


inference:
  inference_data: 'unsw_au_sim+'

  seg_dir_postfix: 'MASKS'
  image_prefix: 'image'
  seg_prefix: 'mask'
  seg_sub_dir: ''

  temp_data_file: '../data/inference/temp/UNSW-AU-Fluo-N2DH-SIM+/clean_data.pkl'

  # - SIM+
#  data_dir: '../data/inference/UNSW-AU-Fluo-N2DH-SIM+'
#  data_dir: '/home/sidorov/Projects/QANetV2/data/inference/BGU-IL-Fluo-N2DH-GOWT1(4)'
  data_dir: '/home/sidorov/Projects/QANetV2/data/inference/DKFZ-GE-Fluo-N2DH-SIM+'
  checkpoint_dir_sim+: '/home/sidorov/Projects/QANetV2/qanet/output/train/tensor_flow_arch_1_float64_SIM+_3_3_pct/checkpoints'

  # - GOWT1
  checkpoint_dir_gowt1: '/home/sidorov/Projects/QANetV2/qanet/output/train/tensor_flow_arch1_float64_GOWT1_5_7_pct/checkpoints'

  # - HeLa
  checkpoint_dir_hela: '/home/sidorov/Projects/QANetV2/qanet/output/train/tensor_flow_arch_1_float64_cyclic_HeLa_3.5_pct/checkpoints'
#  checkpoint_dir: '/home/sidorov/Projects/QANetV2/qanet/output/train/tensor_flow_gauss_blur_2023-01-17_01-10-32/checkpoints'

