general:
  project_name: 'QANetV2'
  name: ''
  debug: False
  configs_dir: './global_configs'
  output_dir: './output'

data:
  reload_data: False
  image_height: 419
  image_width: 419

augmentations:
  crop_height: 128
  crop_width: 128

model:
  in_channels: 1
  out_channels: 1

  architecture: None

  architecture1:
    conv2d_blocks:
      out_channels: [64, 128, 256, 256]
      kernel_sizes: [3, 3, 3, 3]
      dropblock_rate: 0.0
      dropblock_size: 7

    fc_blocks:
      out_features: [128, 128, 1]
      drop_rate: 0.0

  architecture2:
    conv2d_blocks:
      out_channels: [64, 128, 256, 256]
      kernel_sizes: [3, 3, 3, 3]
      dropblock_rate: 0.0
      dropblock_size: 7

    fc_blocks:
      out_features: [128, 128, 1]
      drop_rate: 0.0

  architecture3:
    conv2d_blocks:
      out_channels: [32, 64, 128, 256]
      kernel_sizes: [5, 5, 5, 5]
      dropblock_rate: 0.0
      dropblock_size: 7

    fc_blocks:
      out_features: [512, 1024, 1]
      drop_rate: 0.0

#  activation: 'leaky_relu'
#  activation: 'relu'
  activation: 'swish'
  activation_relu_max_value: None
  activation_relu_negative_slope: 0.0
  activation_relu_threshold: 0.0
  activation_leaky_relu_alpha: 0.3

regularization:
#  kernel_regularizer_type: None
  kernel_regularizer_type: 'l2'
  kernel_regularizer_l1: 0.01
  kernel_regularizer_l2: 0.001
  kernel_regularizer_factor: 0.01
  kernel_regularizer_mode: 'rows'

callbacks:
  wandb_project_name: 'QANet_V2'
  wandb: False

  # - Tensor Board
  tensorboard: True
  tensorboard_launch: False
  tensorboard_write_images: True
  tensorboard_write_steps_per_second: True
  tensorboard_update_freq: 'epoch'
  tensorboard_scalars_log_interval: 1
  tensorboard_images_log_interval: 1

#  progress_log: False
  progress_log: True
  progress_log_interval: 1
  scatter_plot_figsize: (25, 15)
  scatter_plot_fontsize: 40

  # - Terminate on NaN
  terminate_on_nan: True

  # - Checkpoint
#  checkpoint_file_best_model_file: 'best_model.ckpt'  # <- overwrites the second-best model weights in case MODEL_CHECKPOINT_SAVE_BEST_ONLY = True
  checkpoint_file_template: 'checkpoints/cp-{epoch:04d}.ckpt'  # <- may be used in case we want to save all teh check points, and not only the best
  checkpoint_file_best_model: 'checkpoints/best_model.ckpt'  # <- overwrites the second-best model weights in case MODEL_CHECKPOINT_SAVE_BEST_ONLY = True
  checkpoint_file_last_model: 'checkpoints/last_model.ckpt'  # <- overwrites the second-best model weights in case MODEL_CHECKPOINT_SAVE_BEST_ONLY = True
  checkpoint_monitor: 'val_loss'
  checkpoint_verbose: 1
  checkpoint_mode: 'auto'
  checkpoint_save_weights_only: True
  checkpoint_save_freq: 'epoch'
  min_improvement_delta: 0.00001

  # - Early Stopping
  early_stopping: False
  early_stopping_patience: 30
  early_stopping_monitor: 'val_loss'
  early_stopping_min_delta: 0.00001
  early_stopping_mode: 'auto'
  early_stopping_restore_best_weights: True
  early_stopping_verbose: 1

  # - LR Reduce on Plateau
#  reduce_lr_on_plateau: False
  reduce_lr_on_plateau: True
  reduce_lr_on_plateau_patience: 50
  reduce_lr_on_plateau_factor: 0.3
  reduce_lr_on_plateau_monitor: 'val_loss'
  reduce_lr_on_plateau_min_delta: 0.00001
  reduce_lr_on_plateau_cooldown: 0
  reduce_lr_on_plateau_mode: 'auto'
  reduce_lr_on_plateau_verbose: 1
  reduce_lr_on_plateau_min_lr: 0.00001

training:
  load_checkpoint: False
  in_train_augmentation: False

  seg_dir_postfix: 'GT'
  image_prefix: 't'
  seg_prefix: 'man_seg'
  seg_sub_dir: 'SEG'

  data_dir: '../data/train/CytoPack'
  temp_data_file: '../data/train/temp/CytoPack/clean_data.pkl'

  checkpoint_file: ''
  checkpoint_dir: '/home/sidorov/projects/QANetV2/qanet/output/train/tensor_flow_2022-11-24_13-15-16/checkpoints'
  tr_checkpoint_file: '/home/sidorov/projects/QANetV2/qanet/output/train/pytorch_2022-08-08_17-28-30/checkpoints/best_val_loss_chkpt.pth.tar'
  tf_checkpoint_file: 'checkpoints/best_model.ckpt'

  loss: 'mse'
  metrics: []
  epochs: 500
  batch_size: 64
  val_batch_size: 16
  num_train_workers: 8
  val_prop: 0.2
  num_val_workers: 4
  pin_memory: True
  weighted_loss: False

  optimizer_maximize: False
  optimizer_foreach: None
#  optimizer: 'sgd'
  optimizer: 'adam'
  learning_rate_optimization_epochs: 0
  learning_rate: 0.001
  learning_rate_scheduler_reduction_points: [50, 100, 150, 250]
  learning_rate_scheduler_reduction_factor: 0.3
  learning_rate_decay: 0.001
  learning_rate_min: 0.0001
  learning_rate_max: 0.005

  # - LR Reduction Scheduler
#  learning_rate_scheduler: 'None'
  learning_rate_scheduler: 'cosine'
#  learning_rate_scheduler: 'cyclical'
  learning_rate_scheduler_cyclical_init_lr: 0.001
  learning_rate_scheduler_cyclical_max_lr: 0.005
  learning_rate_scheduler_cyclical_step_size: 156 # 2 * 5011 // 64 = 156 # 2 * IMAGES / BATCH_SIZE
  learning_rate_scheduler_decay_steps: 30
  learning_rate_scheduler_patience: [150, 300]
  learning_rate_scheduler_factor: 0.3
  learning_rate_scheduler_min: 1e-9

  optimizer_beta_1: 0.9
  optimizer_beta_2: 0.999
  optimizer_rho: 0.9
  optimizer_amsgrad: False
  optimizer_weight_decay: 0.01
  optimizer_momentum: 0.1
  optimizer_dampening: 0.01
  optimizer_momentum_decay: 0.01
  optimizer_nesterov: True
  optimizer_centered: False

test:
  name: 'test'
  output_dir: ''
  data_name: ''
  gpu_id: -1

  test_sim: False
  test_gowt1: False
  test_hela: False

  checkpoint_file: '/home/sidorov/projects/QANetV2/qanet/output/train/tensorflow/128x128/adam_cyclical_001_05_l2_001_fixed_augs_2023-03-24_00-49-25/checkpoints/best_model.ckpt'

  checkpoint_dir: ''
  # - SIM+
  dataframe_file_sim+: '/home/sidorov/projects/QANetV2/RefModels/Results/Fluo-N2DH-SIM+/seg_scores.csv'
  checkpoint_dir_sim+: '/home/sidorov/projects/QANetV2/qanet/output/train/tensorflow/128x128/dropblock_last_dropout_last_l2_001_arch_2/checkpoints'  # <= error of -4.7%

  # - GOWT1
  dataframe_file_gowt1:  '/home/sidorov/projects/QANetV2/RefModels/Results/Fluo-N2DH-GOWT1/seg_scores.csv'
  checkpoint_dir_gowt1: ''

  # - HeLa
  dataframe_file_hela: '/home/sidorov/projects/QANetV2/RefModels/Results/Fluo-N2DL-HeLa/seg_scores.csv'
  checkpoint_dir_hela: ''


inference:
  seg_dir_postfix: 'MASKS'
  image_prefix: 'image'
  seg_prefix: 'mask'
  seg_sub_dir: ''


  checkpoint_file: '/home/sidorov/projects/QANetV2/qanet/output/train/tensorflow/128x128/adam_001_l2_001_no_special_image_augs_2023-03-26_16-39-36/checkpoints/best_model.ckpt'
  checkpoint_files: [
    '/home/sidorov/projects/QANetV2/qanet/output/train/tensorflow/128x128/cosine_2023-04-01_01-05-45/checkpoints/last_model.ckpt',
    '/home/sidorov/projects/QANetV2/qanet/output/train/tensorflow/128x128/cosine_2023-04-01_01-05-45/checkpoints/best_model.ckpt',
    '/home/sidorov/projects/QANetV2/qanet/output/train/tensorflow/128x128/cyclical_001_005_2023-04-01_01-05-06/checkpoints/last_model.ckpt',
    '/home/sidorov/projects/QANetV2/qanet/output/train/tensorflow/128x128/cyclical_001_005_2023-04-01_01-05-06/checkpoints/best_model.ckpt',
    '/home/sidorov/projects/QANetV2/qanet/output/train/tensorflow/128x128/no_scheduler_lr_001_2023-04-03_01-23-28/checkpoints/last_model.ckpt',
    '/home/sidorov/projects/QANetV2/qanet/output/train/tensorflow/128x128/no_scheduler_lr_001_2023-04-03_01-23-28/checkpoints/best_model.ckpt',
  ]
  temp_data_file: ''
  output_dir: ''
  name: 'inference'
  model_name: ''
  gpu_id: -1

  data_dir: ''
  seg_score: 0.0

  # - SIM+
  # > BGU-IL(3)
  infer_bgu_3_sim: False    # x
  bgu_3_sim_data_dir: ''
  bgu_3_sim_seg_score: 0.811

  # > CVUT-CZ
  infer_cvut_sim: False     # x
  cvut_sim_data_dir: ''
  cvut_sim_seg_score: 0.807

  # > KTH-SE
  infer_kth_sim: False   # v
  kth_sim_data_dir: '/home/sidorov/projects/QANetV2/data/inference/SIM+/KTH-SE-Fluo-N2DH-SIM+'
  kth_sim_seg_score: 0.792

  # > UNSW-AU
  infer_unsw_sim: False     # v
  unsw_sim_data_dir: '/home/sidorov/projects/QANetV2/data/inference/SIM+/UNSW-AU-Fluo-N2DH-SIM+'
  unsw_sim_seg_score: 0.809

  # > DKFZ-GE
  infer_dkfz_sim: False     # v
  dkfz_sim_data_dir: '/home/sidorov/projects/QANetV2/data/inference/SIM+/DKFZ-GE-Fluo-N2DH-SIM+'
  dkfz_sim_seg_score: 0.832


  # - GWOT1
  # > BGU-IL(4)
  infer_bgu_4_gowt1: False  # v
  bgu_4_gowt1_data_dir: '/home/sidorov/projects/QANetV2/data/inference/GOWT1/BGU-IL-Fluo-N2DH-GOWT1(4)'
  bgu_4_gowt1_seg_score: 0.874

  # > BGU-IL(5)
  infer_bgu_5_gowt1: False  # v
  bgu_5_gowt1_data_dir: '/home/sidorov/projects/QANetV2/data/inference/GOWT1/BGU-IL-Fluo-N2DH-GOWT1(5)'
  bgu_5_gowt1_seg_score: 0.920

  # > KTH-SE
  infer_kth_gowt1: False   # v
  kth_gowt1_data_dir: '/home/sidorov/projects/QANetV2/data/inference/GOWT1/KTH-SE-Fluo-N2DH-GOWT1'
  kth_gowt1_seg_score: 0.927

  # > UNSW-AU
  infer_unsw_gowt1: False   # v
  unsw_gowt1_data_dir: '/home/sidorov/projects/QANetV2/data/inference/GOWT1/UNSW-AU-Fluo-N2DH-GOWT1'
  unsw_gowt1_seg_score: 0.933



#  data_dir: '../data/inference/UNSW-AU-Fluo-N2DH-SIM+'
#  data_dir: '/home/sidorov/projects/QANetV2/data/inference/BGU-IL-Fluo-N2DH-GOWT1(4)'
  checkpoint_dir_sim+: '/home/sidorov/projects/QANetV2/qanet/output/train/tensor_flow_arch_1_float64_SIM+_3_3_pct/checkpoints'

  # - GOWT1
  checkpoint_dir_gowt1: '/home/sidorov/projects/QANetV2/qanet/output/train/tensor_flow_arch1_float64_GOWT1_5_7_pct/checkpoints'

  # - HeLa
  checkpoint_dir_hela: '/home/sidorov/projects/QANetV2/qanet/output/train/tensor_flow_arch_1_float64_cyclic_HeLa_3.5_pct/checkpoints'

