import pathlib


# PATHS
DATA_DIR_PATH = pathlib.Path('C:/Users/mchls/Desktop/University/PhD/Projects/QANet/Data/Silver_GT/Fluo-N2DH-GOWT1-ST')
TRAIN_DATA_DIR = DATA_DIR_PATH / 'train'
TEST_DATA_DIR = DATA_DIR_PATH / 'test'
OUTPUT_DIR = pathlib.Path('C:/Users/mchls/Desktop/University/PhD/Projects/QANet/Data/output/augmentations')
CONFIGS_DIR_PATH = pathlib.Path('C:/Users/mchls/Desktop/University/PhD/Projects/QANet/qanet/configs')
RIBCAGE_CONFIGS_FILE_PATH = pathlib.Path('C:/Users/mchls/Desktop/University/PhD/Projects/QANet/qanet/configs/ribcage_configs.yml')

# CONSTANTS
EPSILON = 1e-7

# DATA
VALIDATION_PROPORTION = .2

# PREPROCESSING CONFIGS
STANDARDIZE_IMAGE = False

# - Crops
CROP_SHAPE = (256, 256)
NON_EMPTY_CROPS = True
NON_EMPTY_CROP_THRESHOLD = 5000
MAX_EMPTY_CROPS = 100

# FILTERS CONFIGS
# - CLipped Adaptive Histogram Equalization (CLAHE)
# Enhances the contrast by equalizing the image intensity
APPLY_CLAHE_FILTER = True
CLAHE_CLIP_LIMIT = 2.0
CLAHE_TILE_GRID_SIZE = (8, 8)

# AUGMENTATION CONFIGS
# - Morphological Transforms
EROSION_SIZES = (3, 5, 7, 9)
DILATION_SIZES = (3, 5, 7, 9)
OPENNING_SIZES = (3, 5, 7, 9)
CLOSING_SIZES = (3, 5, 7, 9)

# - Affine Transforms
SCALE_RANGE = (0.01, 0.1)
SHEER_RANGE = (.05, .1)

# CALLBACKS
# - Early Stopping
EARLY_STOPPING_MONITOR = 'val_loss'
EARLY_STOPPING_PATIENCE = 10
EARLY_STOPPING_MIN_DELTA = 0
EARLY_STOPPING_MODE = 'auto'
EARLY_STOPPING_RESTORE_BEST_WEIGHTS = True
EARLY_STOPPING_VERBOSE = 1

# - Tensor Board
TENSOR_BOARD_WRITE_GRAPH = True
TENSOR_BOARD_WRITE_IMAGES = True
TENSOR_BOARD_WRITE_STEPS_PER_SECOND = True
TENSOR_BOARD_UPDATE_FREQ = 'epoch'
TENSOR_BOARD_LOG_INTERVAL = 1

# - LR Reduce
LR_REDUCE_MONITOR = 'val_loss'
LR_REDUCE_FACTOR = 0.1
LR_REDUCE_PATIENCE = 100
LR_REDUCE_MIN_DELTA = 0.0001
LR_REDUCE_COOLDOWN = 0
LR_REDUCE_MIN_LR = 0.0
LR_REDUCE_MODE = 'auto'
LR_REDUCE_VERBOSE = 1

# - Layer Visualization
CONV_VIS_LAYER_FIG_SIZE = (25, 25)
CONV_VIS_LAYER_CMAP = 'gray'
CONV_VIS_LAYER_LOG_INTERVAL = 2

# - Model Checkpoint
MODEL_CHECKPOINT_VERBOSE = 1
MODEL_CHECKPOINT_CHECKPOINT_FREQUENCY = 1000
MODEL_CHECKPOINT_SAVE_WEIGHTS_ONLY = True
