import pathlib
import tensorflow as tf


DEBUG = False

# PATHS
IMAGES_DIR = pathlib.Path('./data/train/imgs')

SEGMENTATIONS_DIR = pathlib.Path('./data/train/segs')

OUTPUT_DIR = pathlib.Path('./output')

CONFIGS_DIR_PATH = pathlib.Path('./configs')

RIBCAGE_CONFIGS_FILE_PATH = pathlib.Path('./configs/ribcage_configs.yml')

# CONSTANTS
EPSILON = 1e-7

# DATA
NUMBER_INDEX_CHARACTERS = 3
SHUFFLE = True

# PREPROCESSING CONFIGS
STANDARDIZE_IMAGE = False

# - Crops
CROP_SIZE = 256
NON_EMPTY_CROPS = True
MIN_OBJECT_AREA = 400
NON_EMPTY_CROP_THRESHOLD = 2000
MAX_EMPTY_CROPS = 10

# FILTERS CONFIGS
# - CLipped Adaptive Histogram Equalization (CLAHE)
# Enhances the contrast by equalizing the image intensity
APPLY_CLAHE_FILTER = True
CLAHE_CLIP_LIMIT = 10.0
CLAHE_TILE_GRID_SIZE = (30, 30)

# AUGMENTATION CONFIGS
# - Morphological Transforms
EROSION_SIZES = (1, 3, 5, 7, 11)
DILATION_SIZES = (1, 3, 5, 7, 11)
OPENING_SIZES = (1, 3, 5, 7, 11)
CLOSING_SIZES = (1, 3, 5, 7, 11)

# - Affine Transforms
SCALE_RANGE = (.01, .2)
SHEER_RANGE = (.05, .2)

# NN
# > Training
OPTIMIZER = tf.keras.optimizers.Adam
LOSS = tf.keras.losses.MeanSquaredError()
METRICS = ['acc']

# = VARIABLES
EPOCHS = 1000
BATCH_SIZE = 32
VALIDATION_PROPORTION = .2
LEARNING_RATE = 1e-4

# > CALLBACKS
# - Tensor Board
TENSOR_BOARD = True
TENSOR_BOARD_WRITE_GRAPH = True
TENSOR_BOARD_WRITE_IMAGES = True
TENSOR_BOARD_WRITE_STEPS_PER_SECOND = True
TENSOR_BOARD_UPDATE_FREQ = 'epoch'
TENSOR_BOARD_LOG_INTERVAL = 1

# -> Scatter Plot
PLOT_SCATTER = True
SCATTER_PLOT_LOG_INTERVAL = 10
SCATTER_PLOT_FIGSIZE = (20, 10)

# -> Launch Tensor Board
TENSOR_BOARD_LAUNCH = True

# - Early Stopping
EARLY_STOPPING = True
EARLY_STOPPING_MONITOR = 'val_loss'
EARLY_STOPPING_PATIENCE = 10
EARLY_STOPPING_MIN_DELTA = 0
EARLY_STOPPING_MODE = 'auto'
EARLY_STOPPING_RESTORE_BEST_WEIGHTS = True
EARLY_STOPPING_VERBOSE = 1

# - Terminate on NaN
TERMINATE_ON_NAN = True

# - LR Reduce
REDUCE_LR_ON_PLATEAU = True
REDUCE_LR_ON_PLATEAU_MONITOR = 'val_loss'
REDUCE_LR_ON_PLATEAU_FACTOR = 0.1
REDUCE_LR_ON_PLATEAU_PATIENCE = 100
REDUCE_LR_ON_PLATEAU_MIN_DELTA = 0.0001
REDUCE_LR_ON_PLATEAU_COOLDOWN = 0
REDUCE_LR_ON_PLATEAU_MIN_LR = 0.0
REDUCE_LR_ON_PLATEAU_MODE = 'auto'
REDUCE_LR_ON_PLATEAU_VERBOSE = 1

# - Model Checkpoint
MODEL_CHECKPOINT = True
MODEL_CHECKPOINT_VERBOSE = 1
MODEL_CHECKPOINT_SAVE_WEIGHTS_ONLY = True
MODEL_CHECKPOINT_CHECKPOINT_FREQUENCY = 100
